### ISSUE TITLE
Empty Building Model Card section

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/course#158]
Hello 👋  
[Building Model Card](https://huggingface.co/course/chapter4/4?fw=pt) section in chapter 4 seems empty. (link goes to nowhere) 
I'll check what's wrong but if anyone knows feel free to do it before me :')  pinging @lewtun here

**Comment by merveenoyan** [comment]
I think he doesn't have bandwidth (?) I will debug later today.

**Comment by lbourdois** [comment]
Hi @merveenoyan 👋

I had mentioned this problem to Lewis last week. I don't know if this can help you to find the cause of the problem but after exploration, I could see that it was the only page of the course not working (for all languages) and that this problem impacted the English page but also the French one (it has not been translated in other languages for the moment).

**Comment by mishig25** [comment]
@lbourdois thanks a lot for reporting this problem! A fix is on the way! 😊

**Comment by mishig25** [comment]
It back live! https://huggingface.co/course/chapter4/4

**Comment by lewtun** [comment]
Yay, thanks @mishig25 🤗 !!
