### ISSUE TITLE
 Add Docs/Demos/Blog Section to the end of Gradio Course

### ISSUE THREAD

**Issue by FarukOzderim** [huggingface/course#207]
I think this kind of Gradio new user flow would be excellent:
1. gradio.app getting_started
2. Gradio Course
3. repo demos, blog posts, gradio docs

[Related slack message](https://huggingface.slack.com/archives/C02QZLG8GMN/p1652345763781429?thread_ts=1652345407.957859&cid=C02QZLG8GMN)
[Related issue](https://github.com/gradio-app/gradio/issues/1271)

cc: @lewtun

**Comment by lewtun** [comment]
Good idea @FarukOzderim ! I think this could go nicely in `chapter9/8.mdx` where we summarise the chapter. For example, we could have a sub-section called "Where to next?" or "Want to learn more?"

Would you like to open a PR with some of the most relevant links?
