### ISSUE TITLE
A button towards the forum

### ISSUE THREAD

**Issue by lbourdois** [huggingface/course#248]
Hi,

I copy/paste the message from our discussion on Discord @lewtun:

What do you think about adding a button at the beginning of web pages that would send the reader to the forum to ask a question if needed?

![image](https://user-images.githubusercontent.com/58078086/173634602-936e7ad5-b136-43b5-a3b4-c3c7bc6a79ac.png)

For example for this image, clicking on the button would take you to https://discuss.huggingface.co/t/chapter-1-questions/6797 

I made this button in 10min on Paint to illustrate this idea, it will probably have to be redrawn.

Have a nice day,

**Comment by lewtun** [comment]
Thanks a lot for the suggestion @lbourdois! I think this type of button would be great not just for the course, but also for our docs in the open-source libraries.

WDYT @mishig25 @gary149 ?

**Comment by mishig25** [comment]
@lbourdois, I think it is a great idea & the button looks amazing!

@lewtun on what pages should the button be added? Only on "Introduction" pages (like [this](https://huggingface.co/course/chapter1/1)) or on all pages? Or "Introduction" + "Summary" pages?

**Comment by lewtun** [comment]
@mishig25 would it be overkill to have it on all course pages? The reason I ask is that I suspect many course readers don't read every section in order, so might miss the forum link.

If that's too much, I like your suggestion to include this on the "Introduction" and "Summary" pages :)

**Comment by gary149** [comment]
I'm ok with it (if it's only for the course)

**Comment by mishig25** [comment]
@lbourdois could you please share the img with us? stp

**Comment by lbourdois** [comment]
![logo_discourse_HF](https://user-images.githubusercontent.com/58078086/186015379-b398162d-ad89-42c0-b4a8-c395690cd2d1.svg)
![logo_discourse_hf](https://user-images.githubusercontent.com/58078086/186015439-fb134b1f-b2ec-46c6-b405-a2b9731363ef.jpg)

The image in .svg (and in .jpg in case I screwed up the .svg)

**Comment by mishig25** [comment]
@lbourdois thanks for the photo, the svg file is not being rendered (maybe corrupted?)

Here is the shields.io version: 

<img src="https://img.shields.io/badge/Ask%20a%20question-f7cf1d.svg?logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgLTEgMTA0IDEwNiI+PGRlZnM+PHN0eWxlPi5jbHMtMXtmaWxsOiMyMzFmMjA7fS5jbHMtMntmaWxsOiNmZmY5YWU7fS5jbHMtM3tmaWxsOiMwMGFlZWY7fS5jbHMtNHtmaWxsOiMwMGE5NGY7fS5jbHMtNXtmaWxsOiNmMTVkMjI7fS5jbHMtNntmaWxsOiNlMzFiMjM7fTwvc3R5bGU+PC9kZWZzPjx0aXRsZT5EaXNjb3Vyc2VfbG9nbzwvdGl0bGU+PGcgaWQ9IkxheWVyXzIiPjxnIGlkPSJMYXllcl8zIj48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik01MS44NywwQzIzLjcxLDAsMCwyMi44MywwLDUxYzAsLjkxLDAsNTIuODEsMCw1Mi44MWw1MS44Ni0uMDVjMjguMTYsMCw1MS0yMy43MSw1MS01MS44N1M4MCwwLDUxLjg3LDBaIi8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNTIuMzcsMTkuNzRBMzEuNjIsMzEuNjIsMCwwLDAsMjQuNTgsNjYuNDFsLTUuNzIsMTguNEwzOS40LDgwLjE3YTMxLjYxLDMxLjYxLDAsMSwwLDEzLTYwLjQzWiIvPjxwYXRoIGNsYXNzPSJjbHMtMyIgZD0iTTc3LjQ1LDMyLjEyYTMxLjYsMzEuNiwwLDAsMS0zOC4wNSw0OEwxOC44Niw4NC44MmwyMC45MS0yLjQ3QTMxLjYsMzEuNiwwLDAsMCw3Ny40NSwzMi4xMloiLz48cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Ik03MS42MywyNi4yOUEzMS42LDMxLjYsMCwwLDEsMzguOCw3OEwxOC44Niw4NC44MiwzOS40LDgwLjE3QTMxLjYsMzEuNiwwLDAsMCw3MS42MywyNi4yOVoiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik0yNi40Nyw2Ny4xMWEzMS42MSwzMS42MSwwLDAsMSw1MS0zNUEzMS42MSwzMS42MSwwLDAsMCwyNC41OCw2Ni40MWwtNS43MiwxOC40WiIvPjxwYXRoIGNsYXNzPSJjbHMtNiIgZD0iTTI0LjU4LDY2LjQxQTMxLjYxLDMxLjYxLDAsMCwxLDcxLjYzLDI2LjI5YTMxLjYxLDMxLjYxLDAsMCwwLTQ5LDM5LjYzbC0zLjc2LDE4LjlaIi8+PC9nPjwvZz48L3N2Zz4=">

**Comment by lbourdois** [comment]
@mishig25 
Your version is so much better. I think it might even deserve to be called "art" compared to some banana 🍌

**Comment by mishig25** [comment]
@lbourdois could you please review https://github.com/huggingface/course/pull/301 

not sure why, github is not letting me add you as a reviewer in #301

**Comment by lbourdois** [comment]
@mishig25 
Everything looks good to me after doing some tests with the bot.
 I think we are on the second best feature of Hugging Face after the HF Hub.

**Comment by mishig25** [comment]
awesome! @lbourdois thanks a lot for the suggestion!
