### ISSUE TITLE
Schematic incorrectly shows model output as model input

### ISSUE THREAD

**Issue by binga** [huggingface/course#276]
The following schematic should show the text in the last block as model output instead of model input.

![image](https://user-images.githubusercontent.com/6457454/177884857-b10e808b-8295-470f-8c25-1c335914c8ca.png)
 
The fix should go into this markdown - https://github.com/huggingface/course/blob/main/chapters/en/chapter2/2.mdx#model-heads-making-sense-out-of-numbers.

**Comment by lewtun** [comment]
Thanks for reporting this issue @binga ! It's now been fixed :)

<img width="788" alt="Screen Shot 2022-10-05 at 16 27 53" src="https://user-images.githubusercontent.com/26859204/194085741-c9c3d953-90fc-4ba2-95dc-630060397eb0.png">
