### ISSUE TITLE
small visual bug

### ISSUE THREAD

**Issue by osbm** [huggingface/course#342]
in chapter 3/3.mdx. There is a misgenerated HTML code block:

![image](https://user-images.githubusercontent.com/74963545/196171189-27702bfc-61e4-4fd5-b1e2-8dfca2742cbd.png)

This may be resolved by turning [this code block](https://github.com/huggingface/course/blob/main/chapters/en/chapter3/3.mdx?plain=1#L157-L159)

````
```
trainer.train()
```
````

into this:

````
```py
trainer.train()
```
````

But I don't know how to test this on my machine.

**Comment by wonhyeongseo** [comment]
Hello @osbm, this issue has been fixed by https://github.com/huggingface/course/pull/370

**Comment by osbm** [comment]
Wonderful, you guys are awesome :)
