### ISSUE TITLE
404 on book link

### ISSUE THREAD

**Issue by davidgilbertson** [huggingface/course#398]
This page: https://github.com/huggingface/course/blob/main/chapters/en/chapter7/3.mdx

Contains: "if you’re interested you can read all about it in Natural Language Processing with Transformers (colloquially known as the Transformers textbook)." but the link is a 404.

Is this the book? https://www.oreilly.com/library/view/natural-language-processing/9781098136789/

**Comment by lewtun** [comment]
G'day David! Thanks for flagging this - it should now be fixed :). Feel free to re-open the issue if not
